name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.x]
        projectName: ["lucky7_1", "lucky7_2", "memory_weakness_1", "memory_weakness_2"]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Git setting
      run: |
        git config --local user.email "story.0206.0803@gmail.com"
        git config --local user.name "ReoHosokawa"

    - name: Install
      run: |
        yarn install
        yarn global add webpack-cli
        yarn global add webpack
    - name: Build & Commit
      run: |
        cd ${{ matrix.projectName }}
        yarn add --dev mini-css-extract-plugin
        yarn build:prod
        git add ../public/*
        git commit -m "${{ matrix.projectName }} build" -a
        git pull origin main
        git push origin main
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
